application: seismic-trail-721
version: 1
runtime: php
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|pdf|xml|html|php))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|pdf|xml|html|php))